[package]
name = "isdb-t-demod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-complex = "0.4"
rustfft = "6.1.0"
reed-solomon = "0.2.1"
clap = { version = "4.4.11", features = ["derive"] }
